import axios from 'axios';

const CLIENT_ID = 'ec3f8387e9e74c419184ed5f7667a1c7';
const CLIENT_SECRET = 'dd4f0946f7984c8ba757af883ee264cc';
const AUTHORIZATION_URL = 'https://accounts.spotify.com/api/token';

const generateToken = async () => {
  const response = await axios({
    url: AUTHORIZATION_URL,
    method: 'post',
    params: {
      grant_type: 'client_credentials',
    },
    headers: {
      Authorization: `Basic ${Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString('base64')}`,
      'Content-Type': 'application/x-www-form-urlencoded',
    },
  });

  const { access_token } = response.data;
  return access_token;
};

// Call the function to generate the token
const token = await generateToken();
console.log(token); // This will output the access token generated by Spotify

export const authorizeEndpoint = 'https://accounts.spotify.com/authorize';
const client_id = 'ec3f8387e9e74c419184ed5f7667a1c7';
const redirect_uri = 'http://localhost:3000/';
const response_type = 'token';

const scopes = [
    "user-top-read",
    "user-read-private",
    "user-library-read",
    "playlist-read-private",
];

export const loginUrl = `${authorizeEndpoint}?client_id=${client_id}&redirect_uri=${redirect_uri}&response_type=${response_type}&access_token=${token}&scopes=${scopes.join('%20')}`;
